Repository MagmaWM/MagmaWM, pull requests merged in 2023-05, with the labels that each got.

#10 Add layer shell support
  src/backends/udev.rs
  src/backends/winit.rs
  src/handlers/input.rs
  src/handlers/mod.rs
  src/handlers/xdg_shell.rs
  src/state.rs
  src/utils/binarytree.rs
  src/utils/focus.rs
  src/utils/mod.rs
  src/utils/tiling.rs
  src/utils/workspace.rs
Labels: enhancement

#9 Add popups
  src/backends/udev.rs
  src/backends/winit.rs
  src/handlers/mod.rs
  src/handlers/xdg_shell.rs
  src/state.rs
Labels: enhancement, needs testing

#12 Better README
  README.md
Labels: documentation, enhancement

#24 implement screencopy
  src/backends/udev.rs
  src/main.rs
  src/protocols/mod.rs
  src/protocols/screencopy/frame.rs
  src/protocols/screencopy/mod.rs
  src/utils/tiling.rs
Labels: enhancement, needs testing

#32 Add automated backend starting
  src/backends/mod.rs
  src/main.rs
Labels: enhancement

#19 Handle LibSeat
  src/backends/udev.rs
  src/handlers/input.rs
  src/protocols/screencopy/frame.rs
Labels: enhancement, needs testing

#38 Handle loosing rendering loop on legacy backend
  src/backends/udev.rs
Labels: bug

#37 fix gbm allocation failing on some gpu's
  src/backends/udev.rs
Labels: bug

#35 Add touchpad support
  src/handlers/input.rs
Labels: enhancement
